# Generated by Django 5.0.6 on 2024-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=150)),
                ('UserName', models.CharField(max_length=100)),
                ('Mobilenumber', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=50)),
                ('Confirmpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
